import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "File-Sharing-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid h-screenbg-gradient-to-br from-indigo-900 via-purple-800 to-pink-900 place-items-center font-inter">
        {children}
      </body>
    </html>
  );
}
